{"metadata":{"role":"symbol","symbolKind":"case","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","roleHeading":"Case","title":"AuthenticationError.failure(_:)","modules":[{"name":"VigramSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"url":"\/documentation\/vigramsdk","abstract":[],"title":"VigramSDK","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"type":"icon","identifier":"logo.png"}],"type":"topic","role":"collection","kind":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"role":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","title":"AuthenticationError","kind":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","title":"AuthenticationError.failure(_:)","role":"symbol"},"logo.png":{"type":"image","identifier":"logo.png","alt":"Vigram logo.","variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}]}}}