{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","title":"AuthenticationError.failure(_:)"},"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"kind":"symbol","sections":[],"references":{"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/logo.png"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"AuthenticationError.failure(_:)"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","type":"topic","title":"VigramSDK","url":"\/documentation\/vigramsdk","images":[{"type":"icon","identifier":"logo.png"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","role":"collection","abstract":[]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"title":"AuthenticationError","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}]}}}